# Generated by Django 4.2.4 on 2023-08-09 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_chat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
